#!/usr/bin/env bash

CWD="$(dirname  ${BASH_SOURCE[0]})"
source "$CWD/config"
UD="$(date '+%x%X' | md5sum | tr -d " -")"
MESSAGE="${1:-$UD}"

VERSION="$STAGE_VERSION$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"

git config user.name "$PROJECT_AUTHOR"
git config user.email "$PROJECT_EMAIL"

if ((git tag | grep "$VERSION") &> /dev/null);then
	git tag -d "$VERSION"
fi

git add .
git commit -m "$MESSAGE"

git tag -a "$VERSION" -m "$MESSAGE"
