#!/usr/bin/env bash

zenity --question\
    --title="Shutdown"\
    --text="Really want to shutdown?"\
    --ok-label="Shutdown"\
    --cancel-label="Keep Running" \
    --icon="system-shutdown"\
    --default-cancel\
    && systemctl poweroff
