#!/usr/bin/env bash

zenity --question\
    --title="Session"\
    --text="Terminate Sway Session?"\
    --ok-label="Logout"\
    --cancel-label="Cancel" \
    --icon="system-log-out"\
    --default-cancel\
    && swaymsg exit
